### ISSUE TITLE
Contribution: Flask-ex (based on this repo)

### ISSUE THREAD

**Issue by renefs** [sclorg/django-ex#136]
Hi,
I made a fork of this repository to run a Flask application on Openshift (https://github.com/renefs/flask-ex) I think It might be helpful for some people using this microframework. My question is: What is needed to add the quickstart here: https://docs.openshift.com/container-platform/3.11/dev_guide/migrating_applications/quickstart_examples.html ?

Cheers,
Rene

**Comment by jfmatth** [comment]
@renefs Can't u just do a PR against that page in the docs?

**Comment by frenzymadness** [comment]
I am closing this issue now but feel free to reopen is this is still relevant.
