### ISSUE TITLE
Changes for django 2.1 support

### ISSUE THREAD

**Issue by jfmatth** [sclorg/django-ex#141]
In starting to build the django 2.x PR for this repo, i ran into a basic issue, django 2.1+ requires SQlite 3.8 or higher, and looks like 3.7 is installed on the python S2I builds.

django 2.0 runs fine with minor changes.

Need SQlite 3.8 installed for 2.1 to run :)

**Comment by frenzymadness** [comment]
The new version in the master branch is compatible with Django 2.2. The older version for 1.11 is in a new branch for backward compatibility.

I am afraid that the new version won't work on RHEL/Centos 7 because the system SQLite there is too old for new Django.
