### ISSUE TITLE
Branch 2.2.x sqlite version problem

### ISSUE THREAD

**Issue by ricco386** [sclorg/django-ex#173]
I have tried to deploy branch 2.2.x to OpenShift with sqlite and the build ended with an error.

Build works fine, but when pod starts it ends in a `CrashLoopBackOff` state. I can see in the logs:

```
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
```

It seems that the default builder image for Python 3.6 has old sqlite version...

**Comment by frenzymadness** [comment]
What version of OS are you using? Django 2.2.x doesn't work on Centos/RHEL 7.

**Comment by ricco386** [comment]
My build was based on ubi7/python-36 which was the default in OpenShift I was using.
