### ISSUE TITLE
module_path, class_name = dotted_path.rsplit('.', 1) ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Sajan390** [sclorg/django-ex#177]
When I try to run django server manage.py . Error occur:
 module_path, class_name = dotted_path.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by frenzymadness** [comment]
Could you please share more info with us? Which branch do you use? How does the complete traceback look like? Which Python version? Is your setup special in any way?

**Comment by Sajan390** [comment]
This problem got resolved anyway. i have been facing another issue lately.
I installed djangorestframework but dont get any response.
![Screenshot (4)](https://user-images.githubusercontent.com/54765581/107312263-13952400-6ab8-11eb-856b-a9db1fca078b.png)


![Screenshot (5)](https://user-images.githubusercontent.com/54765581/107312342-493a0d00-6ab8-11eb-9656-7d526d8dd20e.png)
![Screenshot (6)](https://user-images.githubusercontent.com/54765581/107312344-4b9c6700-6ab8-11eb-884b-8e82141de25a.png)
![Screenshot (7)](https://user-images.githubusercontent.com/54765581/107312346-4c34fd80-6ab8-11eb-8705-a51b5c9d8933.png)
![Screenshot (8)](https://user-images.githubusercontent.com/54765581/107312348-4ccd9400-6ab8-11eb-81ad-815e27b7e9b5.png)

**Comment by frenzymadness** [comment]
The error message is pretty clear here. You are trying to get content for URL "/" but Django sees only definitions for "admin/" and "api/".

Take a look at the documentation for Django and its rest framework for details.

**Comment by Sajan390** [comment]
Thanks for your concern brother.
